[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/upload-image"
  to = "/.netlify/functions/upload-image"
  status = 200
  force = true

[[redirects]]
  from = "/api/upload-site-info"
  to = "/.netlify/functions/upload-site-info"
  status = 200
  force = true
